name: Deploy React Vite App to Vercel

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Optional: Trigger for pull requests to main for preview deployments

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a recent Node.js version compatible with Vite

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25 # Using a community action for Vercel deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          # Set this to true for production deployments on the main branch
          # For PRs, it will automatically create a preview deployment
          prod: ${{ github.ref == 'refs/heads/main' }}

        env:
          # Any environment variables your Vite app needs during build time
          # Example: VITE_API_URL: ${{ secrets.VITE_API_URL }}
          # Remember to prefix with VITE_ for Vite to expose them
          VITE_APP_TITLE: "My Awesome App" # Example of a public env var
